/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    books: Book;
    authors: Author;
    genres: Genre;
    orders: Order;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    genres: GenresSelect<false> | GenresSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'header-settings': HeaderSetting;
    'footer-settings': FooterSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'header-settings': HeaderSettingsSelect<false> | HeaderSettingsSelect<true>;
    'footer-settings': FooterSettingsSelect<false> | FooterSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Last opp et profilbilde for admin-brukeren
   */
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  title: string;
  /**
   * URL-vennlig versjon av tittelen (eks: harry-potter-de-vises-stein)
   */
  slug: string;
  description: string;
  author: number | Author;
  genres?: (number | Genre)[] | null;
  /**
   * Velg én eller flere aldersgrupper som passer for boken
   */
  ageRating: ('barn' | 'ungdom' | 'voksen')[];
  price: number;
  isbn: string;
  publishedYear?: number | null;
  stock: number;
  coverImage?: (number | null) | Media;
  featured?: boolean | null;
  titleStyle?: {
    fontSize?: ('small' | 'normal' | 'large' | 'xlarge' | 'xxlarge') | null;
    fontWeight?: ('normal' | 'semibold' | 'bold') | null;
    textColor?: string | null;
    textAlign?: ('left' | 'center' | 'right') | null;
  };
  descriptionStyle?: {
    fontSize?: ('small' | 'normal' | 'large') | null;
    fontWeight?: ('normal' | 'semibold' | 'bold') | null;
    textColor?: string | null;
    textAlign?: ('left' | 'center' | 'right' | 'justify') | null;
    lineHeight?: ('tight' | 'normal' | 'loose') | null;
  };
  coverImageStyle?: {
    borderRadius?: ('none' | 'small' | 'medium' | 'large' | 'full') | null;
    objectFit?: ('cover' | 'contain' | 'fill') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * URL-vennlig versjon (eks: jo-nesbo)
   */
  slug: string;
  bio?: string | null;
  birthYear?: number | null;
  nationality?: string | null;
  photo?: (number | null) | Media;
  nameStyle?: {
    fontSize?: ('small' | 'normal' | 'large' | 'xlarge') | null;
    fontWeight?: ('normal' | 'semibold' | 'bold') | null;
    textColor?: string | null;
    textAlign?: ('left' | 'center' | 'right') | null;
  };
  bioStyle?: {
    fontSize?: ('small' | 'normal' | 'large') | null;
    fontWeight?: ('normal' | 'semibold' | 'bold') | null;
    textColor?: string | null;
    textAlign?: ('left' | 'center' | 'right' | 'justify') | null;
    lineHeight?: ('tight' | 'normal' | 'loose') | null;
  };
  photoStyle?: {
    borderRadius?: ('none' | 'small' | 'medium' | 'large' | 'full') | null;
    objectFit?: ('cover' | 'contain' | 'fill') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres".
 */
export interface Genre {
  id: number;
  name: string;
  nameStyle?: {
    fontSize?: ('small' | 'normal' | 'large' | 'xlarge') | null;
    fontWeight?: ('normal' | 'semibold' | 'bold') | null;
    textColor?: string | null;
    textAlign?: ('left' | 'center' | 'right') | null;
  };
  slug: string;
  description?: string | null;
  descriptionStyle?: {
    fontSize?: ('small' | 'normal' | 'large') | null;
    fontWeight?: ('normal' | 'semibold' | 'bold') | null;
    textColor?: string | null;
    textAlign?: ('left' | 'center' | 'right' | 'justify') | null;
    lineHeight?: ('tight' | 'normal' | 'loose') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  customerName: string;
  customerEmail: string;
  customerPhone?: string | null;
  items: {
    book: number | Book;
    quantity: number;
    price: number;
    id?: string | null;
  }[];
  totalAmount: number;
  status?: ('pending' | 'confirmed' | 'shipped' | 'delivered') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'genres';
        value: number | Genre;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  author?: T;
  genres?: T;
  ageRating?: T;
  price?: T;
  isbn?: T;
  publishedYear?: T;
  stock?: T;
  coverImage?: T;
  featured?: T;
  titleStyle?:
    | T
    | {
        fontSize?: T;
        fontWeight?: T;
        textColor?: T;
        textAlign?: T;
      };
  descriptionStyle?:
    | T
    | {
        fontSize?: T;
        fontWeight?: T;
        textColor?: T;
        textAlign?: T;
        lineHeight?: T;
      };
  coverImageStyle?:
    | T
    | {
        borderRadius?: T;
        objectFit?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  birthYear?: T;
  nationality?: T;
  photo?: T;
  nameStyle?:
    | T
    | {
        fontSize?: T;
        fontWeight?: T;
        textColor?: T;
        textAlign?: T;
      };
  bioStyle?:
    | T
    | {
        fontSize?: T;
        fontWeight?: T;
        textColor?: T;
        textAlign?: T;
        lineHeight?: T;
      };
  photoStyle?:
    | T
    | {
        borderRadius?: T;
        objectFit?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres_select".
 */
export interface GenresSelect<T extends boolean = true> {
  name?: T;
  nameStyle?:
    | T
    | {
        fontSize?: T;
        fontWeight?: T;
        textColor?: T;
        textAlign?: T;
      };
  slug?: T;
  description?: T;
  descriptionStyle?:
    | T
    | {
        fontSize?: T;
        fontWeight?: T;
        textColor?: T;
        textAlign?: T;
        lineHeight?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  items?:
    | T
    | {
        book?: T;
        quantity?: T;
        price?: T;
        id?: T;
      };
  totalAmount?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  general: {
    siteName: string;
    favicon?: (number | null) | Media;
    pageBackgroundType?: ('solid' | 'gradient') | null;
    /**
     * Velg farge fra listen
     */
    pageBackgroundColor?:
      | (
          | '#ffffff'
          | '#000000'
          | '#f9fafb'
          | '#f3f4f6'
          | '#e5e7eb'
          | '#6b7280'
          | '#374151'
          | '#1f2937'
          | '#fee2e2'
          | '#ef4444'
          | '#dc2626'
          | '#b91c1c'
          | '#be123c'
          | '#991b1b'
          | '#eff6ff'
          | '#dbeafe'
          | '#3b82f6'
          | '#2563eb'
          | '#1e40af'
          | '#1e3a8a'
          | '#1e293b'
          | '#f0fdf4'
          | '#d1fae5'
          | '#10b981'
          | '#059669'
          | '#047857'
          | '#065f46'
          | '#fefce8'
          | '#fef3c7'
          | '#f59e0b'
          | '#d97706'
          | '#d4af37'
          | '#b8860b'
          | '#f97316'
          | '#faf5ff'
          | '#ede9fe'
          | '#8b5cf6'
          | '#7c3aed'
          | '#6d28d9'
          | '#5b21b6'
          | '#fdf2f8'
          | '#fce7f3'
          | '#ec4899'
          | '#db2777'
          | '#be185d'
          | '#d946ef'
          | '#c026d3'
          | '#ecfeff'
          | '#cffafe'
          | '#06b6d4'
          | '#0891b2'
          | '#0e7490'
          | '#fff7ed'
          | '#ffedd5'
          | '#ea580c'
          | '#c2410c'
          | '#e8e8e8'
          | '#c0c0c0'
          | '#a8a8a8'
          | '#b87333'
          | '#cd7f32'
          | '#ff7f50'
          | '#fa8072'
          | '#ffdab9'
          | '#e6e6fa'
          | '#98ff98'
          | '#808000'
          | '#008080'
          | '#4b0082'
        )
      | null;
    /**
     * 0 = fullstendig gjennomsiktig, 100 = fullstendig ugjennomsiktig
     */
    pageBackgroundColorOpacity?: number | null;
    pageGradientColor1?:
      | (
          | '#ffffff'
          | '#000000'
          | '#f9fafb'
          | '#f3f4f6'
          | '#e5e7eb'
          | '#6b7280'
          | '#374151'
          | '#1f2937'
          | '#fee2e2'
          | '#ef4444'
          | '#dc2626'
          | '#b91c1c'
          | '#be123c'
          | '#991b1b'
          | '#eff6ff'
          | '#dbeafe'
          | '#3b82f6'
          | '#2563eb'
          | '#1e40af'
          | '#1e3a8a'
          | '#1e293b'
          | '#f0fdf4'
          | '#d1fae5'
          | '#10b981'
          | '#059669'
          | '#047857'
          | '#065f46'
          | '#fefce8'
          | '#fef3c7'
          | '#f59e0b'
          | '#d97706'
          | '#d4af37'
          | '#b8860b'
          | '#f97316'
          | '#faf5ff'
          | '#ede9fe'
          | '#8b5cf6'
          | '#7c3aed'
          | '#6d28d9'
          | '#5b21b6'
          | '#fdf2f8'
          | '#fce7f3'
          | '#ec4899'
          | '#db2777'
          | '#be185d'
          | '#d946ef'
          | '#c026d3'
          | '#ecfeff'
          | '#cffafe'
          | '#06b6d4'
          | '#0891b2'
          | '#0e7490'
          | '#fff7ed'
          | '#ffedd5'
          | '#ea580c'
          | '#c2410c'
          | '#e8e8e8'
          | '#c0c0c0'
          | '#a8a8a8'
          | '#b87333'
          | '#cd7f32'
          | '#ff7f50'
          | '#fa8072'
          | '#ffdab9'
          | '#e6e6fa'
          | '#98ff98'
          | '#808000'
          | '#008080'
          | '#4b0082'
        )
      | null;
    pageGradientColor2?:
      | (
          | '#ffffff'
          | '#000000'
          | '#f9fafb'
          | '#f3f4f6'
          | '#e5e7eb'
          | '#6b7280'
          | '#374151'
          | '#1f2937'
          | '#fee2e2'
          | '#ef4444'
          | '#dc2626'
          | '#b91c1c'
          | '#be123c'
          | '#991b1b'
          | '#eff6ff'
          | '#dbeafe'
          | '#3b82f6'
          | '#2563eb'
          | '#1e40af'
          | '#1e3a8a'
          | '#1e293b'
          | '#f0fdf4'
          | '#d1fae5'
          | '#10b981'
          | '#059669'
          | '#047857'
          | '#065f46'
          | '#fefce8'
          | '#fef3c7'
          | '#f59e0b'
          | '#d97706'
          | '#d4af37'
          | '#b8860b'
          | '#f97316'
          | '#faf5ff'
          | '#ede9fe'
          | '#8b5cf6'
          | '#7c3aed'
          | '#6d28d9'
          | '#5b21b6'
          | '#fdf2f8'
          | '#fce7f3'
          | '#ec4899'
          | '#db2777'
          | '#be185d'
          | '#d946ef'
          | '#c026d3'
          | '#ecfeff'
          | '#cffafe'
          | '#06b6d4'
          | '#0891b2'
          | '#0e7490'
          | '#fff7ed'
          | '#ffedd5'
          | '#ea580c'
          | '#c2410c'
          | '#e8e8e8'
          | '#c0c0c0'
          | '#a8a8a8'
          | '#b87333'
          | '#cd7f32'
          | '#ff7f50'
          | '#fa8072'
          | '#ffdab9'
          | '#e6e6fa'
          | '#98ff98'
          | '#808000'
          | '#008080'
          | '#4b0082'
        )
      | null;
    /**
     * Vinkel for gradient (0-360 grader)
     */
    pageGradientAngle?: number | null;
  };
  /**
   * Legg til seksjoner som vises på hjemmesiden i rekkefølge
   */
  homeSections?:
    | {
        sectionType: 'hero' | 'featured' | 'categories' | 'text' | 'banner';
        visible?: boolean | null;
        hero?: {
          title: string;
          titleStyle?: {
            fontSize?: ('small' | 'normal' | 'large' | 'xlarge' | 'xxlarge') | null;
            fontWeight?: ('normal' | 'semibold' | 'bold') | null;
            textColor?:
              | (
                  | '#ffffff'
                  | '#000000'
                  | '#f9fafb'
                  | '#f3f4f6'
                  | '#e5e7eb'
                  | '#6b7280'
                  | '#374151'
                  | '#1f2937'
                  | '#fee2e2'
                  | '#ef4444'
                  | '#dc2626'
                  | '#b91c1c'
                  | '#be123c'
                  | '#991b1b'
                  | '#eff6ff'
                  | '#dbeafe'
                  | '#3b82f6'
                  | '#2563eb'
                  | '#1e40af'
                  | '#1e3a8a'
                  | '#1e293b'
                  | '#f0fdf4'
                  | '#d1fae5'
                  | '#10b981'
                  | '#059669'
                  | '#047857'
                  | '#065f46'
                  | '#fefce8'
                  | '#fef3c7'
                  | '#f59e0b'
                  | '#d97706'
                  | '#d4af37'
                  | '#b8860b'
                  | '#f97316'
                  | '#faf5ff'
                  | '#ede9fe'
                  | '#8b5cf6'
                  | '#7c3aed'
                  | '#6d28d9'
                  | '#5b21b6'
                  | '#fdf2f8'
                  | '#fce7f3'
                  | '#ec4899'
                  | '#db2777'
                  | '#be185d'
                  | '#d946ef'
                  | '#c026d3'
                  | '#ecfeff'
                  | '#cffafe'
                  | '#06b6d4'
                  | '#0891b2'
                  | '#0e7490'
                  | '#fff7ed'
                  | '#ffedd5'
                  | '#ea580c'
                  | '#c2410c'
                  | '#e8e8e8'
                  | '#c0c0c0'
                  | '#a8a8a8'
                  | '#b87333'
                  | '#cd7f32'
                  | '#ff7f50'
                  | '#fa8072'
                  | '#ffdab9'
                  | '#e6e6fa'
                  | '#98ff98'
                  | '#808000'
                  | '#008080'
                  | '#4b0082'
                )
              | null;
            textAlign?: ('left' | 'center' | 'right') | null;
          };
          subtitle?: string | null;
          subtitleStyle?: {
            fontSize?: ('small' | 'normal' | 'large' | 'xlarge') | null;
            fontWeight?: ('normal' | 'semibold' | 'bold') | null;
            textColor?:
              | (
                  | '#ffffff'
                  | '#000000'
                  | '#f9fafb'
                  | '#f3f4f6'
                  | '#e5e7eb'
                  | '#6b7280'
                  | '#374151'
                  | '#1f2937'
                  | '#fee2e2'
                  | '#ef4444'
                  | '#dc2626'
                  | '#b91c1c'
                  | '#be123c'
                  | '#991b1b'
                  | '#eff6ff'
                  | '#dbeafe'
                  | '#3b82f6'
                  | '#2563eb'
                  | '#1e40af'
                  | '#1e3a8a'
                  | '#1e293b'
                  | '#f0fdf4'
                  | '#d1fae5'
                  | '#10b981'
                  | '#059669'
                  | '#047857'
                  | '#065f46'
                  | '#fefce8'
                  | '#fef3c7'
                  | '#f59e0b'
                  | '#d97706'
                  | '#d4af37'
                  | '#b8860b'
                  | '#f97316'
                  | '#faf5ff'
                  | '#ede9fe'
                  | '#8b5cf6'
                  | '#7c3aed'
                  | '#6d28d9'
                  | '#5b21b6'
                  | '#fdf2f8'
                  | '#fce7f3'
                  | '#ec4899'
                  | '#db2777'
                  | '#be185d'
                  | '#d946ef'
                  | '#c026d3'
                  | '#ecfeff'
                  | '#cffafe'
                  | '#06b6d4'
                  | '#0891b2'
                  | '#0e7490'
                  | '#fff7ed'
                  | '#ffedd5'
                  | '#ea580c'
                  | '#c2410c'
                  | '#e8e8e8'
                  | '#c0c0c0'
                  | '#a8a8a8'
                  | '#b87333'
                  | '#cd7f32'
                  | '#ff7f50'
                  | '#fa8072'
                  | '#ffdab9'
                  | '#e6e6fa'
                  | '#98ff98'
                  | '#808000'
                  | '#008080'
                  | '#4b0082'
                )
              | null;
            textAlign?: ('left' | 'center' | 'right') | null;
          };
          buttonText?: string | null;
          buttonStyle?: {
            /**
             * Velg farge fra listen
             */
            backgroundColor?:
              | (
                  | '#ffffff'
                  | '#000000'
                  | '#f9fafb'
                  | '#f3f4f6'
                  | '#e5e7eb'
                  | '#6b7280'
                  | '#374151'
                  | '#1f2937'
                  | '#fee2e2'
                  | '#ef4444'
                  | '#dc2626'
                  | '#b91c1c'
                  | '#be123c'
                  | '#991b1b'
                  | '#eff6ff'
                  | '#dbeafe'
                  | '#3b82f6'
                  | '#2563eb'
                  | '#1e40af'
                  | '#1e3a8a'
                  | '#1e293b'
                  | '#f0fdf4'
                  | '#d1fae5'
                  | '#10b981'
                  | '#059669'
                  | '#047857'
                  | '#065f46'
                  | '#fefce8'
                  | '#fef3c7'
                  | '#f59e0b'
                  | '#d97706'
                  | '#d4af37'
                  | '#b8860b'
                  | '#f97316'
                  | '#faf5ff'
                  | '#ede9fe'
                  | '#8b5cf6'
                  | '#7c3aed'
                  | '#6d28d9'
                  | '#5b21b6'
                  | '#fdf2f8'
                  | '#fce7f3'
                  | '#ec4899'
                  | '#db2777'
                  | '#be185d'
                  | '#d946ef'
                  | '#c026d3'
                  | '#ecfeff'
                  | '#cffafe'
                  | '#06b6d4'
                  | '#0891b2'
                  | '#0e7490'
                  | '#fff7ed'
                  | '#ffedd5'
                  | '#ea580c'
                  | '#c2410c'
                  | '#e8e8e8'
                  | '#c0c0c0'
                  | '#a8a8a8'
                  | '#b87333'
                  | '#cd7f32'
                  | '#ff7f50'
                  | '#fa8072'
                  | '#ffdab9'
                  | '#e6e6fa'
                  | '#98ff98'
                  | '#808000'
                  | '#008080'
                  | '#4b0082'
                )
              | null;
            /**
             * 0 = fullstendig gjennomsiktig, 100 = fullstendig ugjennomsiktig
             */
            backgroundColorOpacity?: number | null;
            textColor?:
              | (
                  | '#ffffff'
                  | '#000000'
                  | '#f9fafb'
                  | '#f3f4f6'
                  | '#e5e7eb'
                  | '#6b7280'
                  | '#374151'
                  | '#1f2937'
                  | '#fee2e2'
                  | '#ef4444'
                  | '#dc2626'
                  | '#b91c1c'
                  | '#be123c'
                  | '#991b1b'
                  | '#eff6ff'
                  | '#dbeafe'
                  | '#3b82f6'
                  | '#2563eb'
                  | '#1e40af'
                  | '#1e3a8a'
                  | '#1e293b'
                  | '#f0fdf4'
                  | '#d1fae5'
                  | '#10b981'
                  | '#059669'
                  | '#047857'
                  | '#065f46'
                  | '#fefce8'
                  | '#fef3c7'
                  | '#f59e0b'
                  | '#d97706'
                  | '#d4af37'
                  | '#b8860b'
                  | '#f97316'
                  | '#faf5ff'
                  | '#ede9fe'
                  | '#8b5cf6'
                  | '#7c3aed'
                  | '#6d28d9'
                  | '#5b21b6'
                  | '#fdf2f8'
                  | '#fce7f3'
                  | '#ec4899'
                  | '#db2777'
                  | '#be185d'
                  | '#d946ef'
                  | '#c026d3'
                  | '#ecfeff'
                  | '#cffafe'
                  | '#06b6d4'
                  | '#0891b2'
                  | '#0e7490'
                  | '#fff7ed'
                  | '#ffedd5'
                  | '#ea580c'
                  | '#c2410c'
                  | '#e8e8e8'
                  | '#c0c0c0'
                  | '#a8a8a8'
                  | '#b87333'
                  | '#cd7f32'
                  | '#ff7f50'
                  | '#fa8072'
                  | '#ffdab9'
                  | '#e6e6fa'
                  | '#98ff98'
                  | '#808000'
                  | '#008080'
                  | '#4b0082'
                )
              | null;
            fontSize?: ('small' | 'normal' | 'large') | null;
            padding?: ('small' | 'medium' | 'large') | null;
            borderRadius?: ('none' | 'small' | 'medium' | 'large' | 'full') | null;
          };
          buttonLink?: string | null;
          backgroundType: 'gradient' | 'image' | 'video';
          backgroundImage?: (number | null) | Media;
          /**
           * Last opp video (MP4 anbefales)
           */
          backgroundVideo?: (number | null) | Media;
          gradientColor1?:
            | (
                | '#ffffff'
                | '#000000'
                | '#f9fafb'
                | '#f3f4f6'
                | '#e5e7eb'
                | '#6b7280'
                | '#374151'
                | '#1f2937'
                | '#fee2e2'
                | '#ef4444'
                | '#dc2626'
                | '#b91c1c'
                | '#be123c'
                | '#991b1b'
                | '#eff6ff'
                | '#dbeafe'
                | '#3b82f6'
                | '#2563eb'
                | '#1e40af'
                | '#1e3a8a'
                | '#1e293b'
                | '#f0fdf4'
                | '#d1fae5'
                | '#10b981'
                | '#059669'
                | '#047857'
                | '#065f46'
                | '#fefce8'
                | '#fef3c7'
                | '#f59e0b'
                | '#d97706'
                | '#d4af37'
                | '#b8860b'
                | '#f97316'
                | '#faf5ff'
                | '#ede9fe'
                | '#8b5cf6'
                | '#7c3aed'
                | '#6d28d9'
                | '#5b21b6'
                | '#fdf2f8'
                | '#fce7f3'
                | '#ec4899'
                | '#db2777'
                | '#be185d'
                | '#d946ef'
                | '#c026d3'
                | '#ecfeff'
                | '#cffafe'
                | '#06b6d4'
                | '#0891b2'
                | '#0e7490'
                | '#fff7ed'
                | '#ffedd5'
                | '#ea580c'
                | '#c2410c'
                | '#e8e8e8'
                | '#c0c0c0'
                | '#a8a8a8'
                | '#b87333'
                | '#cd7f32'
                | '#ff7f50'
                | '#fa8072'
                | '#ffdab9'
                | '#e6e6fa'
                | '#98ff98'
                | '#808000'
                | '#008080'
                | '#4b0082'
              )
            | null;
          gradientColor2?:
            | (
                | '#ffffff'
                | '#000000'
                | '#f9fafb'
                | '#f3f4f6'
                | '#e5e7eb'
                | '#6b7280'
                | '#374151'
                | '#1f2937'
                | '#fee2e2'
                | '#ef4444'
                | '#dc2626'
                | '#b91c1c'
                | '#be123c'
                | '#991b1b'
                | '#eff6ff'
                | '#dbeafe'
                | '#3b82f6'
                | '#2563eb'
                | '#1e40af'
                | '#1e3a8a'
                | '#1e293b'
                | '#f0fdf4'
                | '#d1fae5'
                | '#10b981'
                | '#059669'
                | '#047857'
                | '#065f46'
                | '#fefce8'
                | '#fef3c7'
                | '#f59e0b'
                | '#d97706'
                | '#d4af37'
                | '#b8860b'
                | '#f97316'
                | '#faf5ff'
                | '#ede9fe'
                | '#8b5cf6'
                | '#7c3aed'
                | '#6d28d9'
                | '#5b21b6'
                | '#fdf2f8'
                | '#fce7f3'
                | '#ec4899'
                | '#db2777'
                | '#be185d'
                | '#d946ef'
                | '#c026d3'
                | '#ecfeff'
                | '#cffafe'
                | '#06b6d4'
                | '#0891b2'
                | '#0e7490'
                | '#fff7ed'
                | '#ffedd5'
                | '#ea580c'
                | '#c2410c'
                | '#e8e8e8'
                | '#c0c0c0'
                | '#a8a8a8'
                | '#b87333'
                | '#cd7f32'
                | '#ff7f50'
                | '#fa8072'
                | '#ffdab9'
                | '#e6e6fa'
                | '#98ff98'
                | '#808000'
                | '#008080'
                | '#4b0082'
              )
            | null;
          /**
           * Vinkel for gradient (0-360 grader)
           */
          gradientAngle?: number | null;
          height: 'short' | 'normal' | 'tall' | 'full';
          textAlign?: ('left' | 'center' | 'right') | null;
          padding?: ('none' | 'small' | 'medium' | 'large') | null;
        };
        featured?: {
          title?: string | null;
          titleStyle?: {
            fontSize?: ('small' | 'normal' | 'large' | 'xlarge') | null;
            fontWeight?: ('normal' | 'semibold' | 'bold') | null;
            textColor?:
              | (
                  | '#ffffff'
                  | '#000000'
                  | '#f9fafb'
                  | '#f3f4f6'
                  | '#e5e7eb'
                  | '#6b7280'
                  | '#374151'
                  | '#1f2937'
                  | '#fee2e2'
                  | '#ef4444'
                  | '#dc2626'
                  | '#b91c1c'
                  | '#be123c'
                  | '#991b1b'
                  | '#eff6ff'
                  | '#dbeafe'
                  | '#3b82f6'
                  | '#2563eb'
                  | '#1e40af'
                  | '#1e3a8a'
                  | '#1e293b'
                  | '#f0fdf4'
                  | '#d1fae5'
                  | '#10b981'
                  | '#059669'
                  | '#047857'
                  | '#065f46'
                  | '#fefce8'
                  | '#fef3c7'
                  | '#f59e0b'
                  | '#d97706'
                  | '#d4af37'
                  | '#b8860b'
                  | '#f97316'
                  | '#faf5ff'
                  | '#ede9fe'
                  | '#8b5cf6'
                  | '#7c3aed'
                  | '#6d28d9'
                  | '#5b21b6'
                  | '#fdf2f8'
                  | '#fce7f3'
                  | '#ec4899'
                  | '#db2777'
                  | '#be185d'
                  | '#d946ef'
                  | '#c026d3'
                  | '#ecfeff'
                  | '#cffafe'
                  | '#06b6d4'
                  | '#0891b2'
                  | '#0e7490'
                  | '#fff7ed'
                  | '#ffedd5'
                  | '#ea580c'
                  | '#c2410c'
                  | '#e8e8e8'
                  | '#c0c0c0'
                  | '#a8a8a8'
                  | '#b87333'
                  | '#cd7f32'
                  | '#ff7f50'
                  | '#fa8072'
                  | '#ffdab9'
                  | '#e6e6fa'
                  | '#98ff98'
                  | '#808000'
                  | '#008080'
                  | '#4b0082'
                )
              | null;
            textAlign?: ('left' | 'center' | 'right') | null;
          };
          limit?: number | null;
          /**
           * Velg farge fra listen
           */
          backgroundColor?:
            | (
                | '#ffffff'
                | '#000000'
                | '#f9fafb'
                | '#f3f4f6'
                | '#e5e7eb'
                | '#6b7280'
                | '#374151'
                | '#1f2937'
                | '#fee2e2'
                | '#ef4444'
                | '#dc2626'
                | '#b91c1c'
                | '#be123c'
                | '#991b1b'
                | '#eff6ff'
                | '#dbeafe'
                | '#3b82f6'
                | '#2563eb'
                | '#1e40af'
                | '#1e3a8a'
                | '#1e293b'
                | '#f0fdf4'
                | '#d1fae5'
                | '#10b981'
                | '#059669'
                | '#047857'
                | '#065f46'
                | '#fefce8'
                | '#fef3c7'
                | '#f59e0b'
                | '#d97706'
                | '#d4af37'
                | '#b8860b'
                | '#f97316'
                | '#faf5ff'
                | '#ede9fe'
                | '#8b5cf6'
                | '#7c3aed'
                | '#6d28d9'
                | '#5b21b6'
                | '#fdf2f8'
                | '#fce7f3'
                | '#ec4899'
                | '#db2777'
                | '#be185d'
                | '#d946ef'
                | '#c026d3'
                | '#ecfeff'
                | '#cffafe'
                | '#06b6d4'
                | '#0891b2'
                | '#0e7490'
                | '#fff7ed'
                | '#ffedd5'
                | '#ea580c'
                | '#c2410c'
                | '#e8e8e8'
                | '#c0c0c0'
                | '#a8a8a8'
                | '#b87333'
                | '#cd7f32'
                | '#ff7f50'
                | '#fa8072'
                | '#ffdab9'
                | '#e6e6fa'
                | '#98ff98'
                | '#808000'
                | '#008080'
                | '#4b0082'
              )
            | null;
          /**
           * 0 = fullstendig gjennomsiktig, 100 = fullstendig ugjennomsiktig
           */
          backgroundColorOpacity?: number | null;
          sectionPadding?: ('none' | 'small' | 'medium' | 'large') | null;
        };
        categories?: {
          title?: string | null;
          titleStyle?: {
            fontSize?: ('small' | 'normal' | 'large' | 'xlarge') | null;
            fontWeight?: ('normal' | 'semibold' | 'bold') | null;
            textColor?:
              | (
                  | '#ffffff'
                  | '#000000'
                  | '#f9fafb'
                  | '#f3f4f6'
                  | '#e5e7eb'
                  | '#6b7280'
                  | '#374151'
                  | '#1f2937'
                  | '#fee2e2'
                  | '#ef4444'
                  | '#dc2626'
                  | '#b91c1c'
                  | '#be123c'
                  | '#991b1b'
                  | '#eff6ff'
                  | '#dbeafe'
                  | '#3b82f6'
                  | '#2563eb'
                  | '#1e40af'
                  | '#1e3a8a'
                  | '#1e293b'
                  | '#f0fdf4'
                  | '#d1fae5'
                  | '#10b981'
                  | '#059669'
                  | '#047857'
                  | '#065f46'
                  | '#fefce8'
                  | '#fef3c7'
                  | '#f59e0b'
                  | '#d97706'
                  | '#d4af37'
                  | '#b8860b'
                  | '#f97316'
                  | '#faf5ff'
                  | '#ede9fe'
                  | '#8b5cf6'
                  | '#7c3aed'
                  | '#6d28d9'
                  | '#5b21b6'
                  | '#fdf2f8'
                  | '#fce7f3'
                  | '#ec4899'
                  | '#db2777'
                  | '#be185d'
                  | '#d946ef'
                  | '#c026d3'
                  | '#ecfeff'
                  | '#cffafe'
                  | '#06b6d4'
                  | '#0891b2'
                  | '#0e7490'
                  | '#fff7ed'
                  | '#ffedd5'
                  | '#ea580c'
                  | '#c2410c'
                  | '#e8e8e8'
                  | '#c0c0c0'
                  | '#a8a8a8'
                  | '#b87333'
                  | '#cd7f32'
                  | '#ff7f50'
                  | '#fa8072'
                  | '#ffdab9'
                  | '#e6e6fa'
                  | '#98ff98'
                  | '#808000'
                  | '#008080'
                  | '#4b0082'
                )
              | null;
            textAlign?: ('left' | 'center' | 'right') | null;
          };
          /**
           * Velg farge fra listen
           */
          backgroundColor?:
            | (
                | '#ffffff'
                | '#000000'
                | '#f9fafb'
                | '#f3f4f6'
                | '#e5e7eb'
                | '#6b7280'
                | '#374151'
                | '#1f2937'
                | '#fee2e2'
                | '#ef4444'
                | '#dc2626'
                | '#b91c1c'
                | '#be123c'
                | '#991b1b'
                | '#eff6ff'
                | '#dbeafe'
                | '#3b82f6'
                | '#2563eb'
                | '#1e40af'
                | '#1e3a8a'
                | '#1e293b'
                | '#f0fdf4'
                | '#d1fae5'
                | '#10b981'
                | '#059669'
                | '#047857'
                | '#065f46'
                | '#fefce8'
                | '#fef3c7'
                | '#f59e0b'
                | '#d97706'
                | '#d4af37'
                | '#b8860b'
                | '#f97316'
                | '#faf5ff'
                | '#ede9fe'
                | '#8b5cf6'
                | '#7c3aed'
                | '#6d28d9'
                | '#5b21b6'
                | '#fdf2f8'
                | '#fce7f3'
                | '#ec4899'
                | '#db2777'
                | '#be185d'
                | '#d946ef'
                | '#c026d3'
                | '#ecfeff'
                | '#cffafe'
                | '#06b6d4'
                | '#0891b2'
                | '#0e7490'
                | '#fff7ed'
                | '#ffedd5'
                | '#ea580c'
                | '#c2410c'
                | '#e8e8e8'
                | '#c0c0c0'
                | '#a8a8a8'
                | '#b87333'
                | '#cd7f32'
                | '#ff7f50'
                | '#fa8072'
                | '#ffdab9'
                | '#e6e6fa'
                | '#98ff98'
                | '#808000'
                | '#008080'
                | '#4b0082'
              )
            | null;
          /**
           * 0 = fullstendig gjennomsiktig, 100 = fullstendig ugjennomsiktig
           */
          backgroundColorOpacity?: number | null;
          sectionPadding?: ('none' | 'small' | 'medium' | 'large') | null;
        };
        textSection?: {
          title?: string | null;
          titleStyle?: {
            fontSize?: ('small' | 'normal' | 'large' | 'xlarge') | null;
            fontWeight?: ('normal' | 'semibold' | 'bold') | null;
            textColor?:
              | (
                  | '#ffffff'
                  | '#000000'
                  | '#f9fafb'
                  | '#f3f4f6'
                  | '#e5e7eb'
                  | '#6b7280'
                  | '#374151'
                  | '#1f2937'
                  | '#fee2e2'
                  | '#ef4444'
                  | '#dc2626'
                  | '#b91c1c'
                  | '#be123c'
                  | '#991b1b'
                  | '#eff6ff'
                  | '#dbeafe'
                  | '#3b82f6'
                  | '#2563eb'
                  | '#1e40af'
                  | '#1e3a8a'
                  | '#1e293b'
                  | '#f0fdf4'
                  | '#d1fae5'
                  | '#10b981'
                  | '#059669'
                  | '#047857'
                  | '#065f46'
                  | '#fefce8'
                  | '#fef3c7'
                  | '#f59e0b'
                  | '#d97706'
                  | '#d4af37'
                  | '#b8860b'
                  | '#f97316'
                  | '#faf5ff'
                  | '#ede9fe'
                  | '#8b5cf6'
                  | '#7c3aed'
                  | '#6d28d9'
                  | '#5b21b6'
                  | '#fdf2f8'
                  | '#fce7f3'
                  | '#ec4899'
                  | '#db2777'
                  | '#be185d'
                  | '#d946ef'
                  | '#c026d3'
                  | '#ecfeff'
                  | '#cffafe'
                  | '#06b6d4'
                  | '#0891b2'
                  | '#0e7490'
                  | '#fff7ed'
                  | '#ffedd5'
                  | '#ea580c'
                  | '#c2410c'
                  | '#e8e8e8'
                  | '#c0c0c0'
                  | '#a8a8a8'
                  | '#b87333'
                  | '#cd7f32'
                  | '#ff7f50'
                  | '#fa8072'
                  | '#ffdab9'
                  | '#e6e6fa'
                  | '#98ff98'
                  | '#808000'
                  | '#008080'
                  | '#4b0082'
                )
              | null;
            textAlign?: ('left' | 'center' | 'right') | null;
          };
          content: string;
          contentStyle?: {
            fontSize?: ('small' | 'normal' | 'large') | null;
            fontWeight?: ('normal' | 'semibold' | 'bold') | null;
            textColor?:
              | (
                  | '#ffffff'
                  | '#000000'
                  | '#f9fafb'
                  | '#f3f4f6'
                  | '#e5e7eb'
                  | '#6b7280'
                  | '#374151'
                  | '#1f2937'
                  | '#fee2e2'
                  | '#ef4444'
                  | '#dc2626'
                  | '#b91c1c'
                  | '#be123c'
                  | '#991b1b'
                  | '#eff6ff'
                  | '#dbeafe'
                  | '#3b82f6'
                  | '#2563eb'
                  | '#1e40af'
                  | '#1e3a8a'
                  | '#1e293b'
                  | '#f0fdf4'
                  | '#d1fae5'
                  | '#10b981'
                  | '#059669'
                  | '#047857'
                  | '#065f46'
                  | '#fefce8'
                  | '#fef3c7'
                  | '#f59e0b'
                  | '#d97706'
                  | '#d4af37'
                  | '#b8860b'
                  | '#f97316'
                  | '#faf5ff'
                  | '#ede9fe'
                  | '#8b5cf6'
                  | '#7c3aed'
                  | '#6d28d9'
                  | '#5b21b6'
                  | '#fdf2f8'
                  | '#fce7f3'
                  | '#ec4899'
                  | '#db2777'
                  | '#be185d'
                  | '#d946ef'
                  | '#c026d3'
                  | '#ecfeff'
                  | '#cffafe'
                  | '#06b6d4'
                  | '#0891b2'
                  | '#0e7490'
                  | '#fff7ed'
                  | '#ffedd5'
                  | '#ea580c'
                  | '#c2410c'
                  | '#e8e8e8'
                  | '#c0c0c0'
                  | '#a8a8a8'
                  | '#b87333'
                  | '#cd7f32'
                  | '#ff7f50'
                  | '#fa8072'
                  | '#ffdab9'
                  | '#e6e6fa'
                  | '#98ff98'
                  | '#808000'
                  | '#008080'
                  | '#4b0082'
                )
              | null;
            textAlign?: ('left' | 'center' | 'right' | 'justify') | null;
            lineHeight?: ('tight' | 'normal' | 'loose') | null;
          };
          /**
           * Velg farge fra listen
           */
          backgroundColor?:
            | (
                | '#ffffff'
                | '#000000'
                | '#f9fafb'
                | '#f3f4f6'
                | '#e5e7eb'
                | '#6b7280'
                | '#374151'
                | '#1f2937'
                | '#fee2e2'
                | '#ef4444'
                | '#dc2626'
                | '#b91c1c'
                | '#be123c'
                | '#991b1b'
                | '#eff6ff'
                | '#dbeafe'
                | '#3b82f6'
                | '#2563eb'
                | '#1e40af'
                | '#1e3a8a'
                | '#1e293b'
                | '#f0fdf4'
                | '#d1fae5'
                | '#10b981'
                | '#059669'
                | '#047857'
                | '#065f46'
                | '#fefce8'
                | '#fef3c7'
                | '#f59e0b'
                | '#d97706'
                | '#d4af37'
                | '#b8860b'
                | '#f97316'
                | '#faf5ff'
                | '#ede9fe'
                | '#8b5cf6'
                | '#7c3aed'
                | '#6d28d9'
                | '#5b21b6'
                | '#fdf2f8'
                | '#fce7f3'
                | '#ec4899'
                | '#db2777'
                | '#be185d'
                | '#d946ef'
                | '#c026d3'
                | '#ecfeff'
                | '#cffafe'
                | '#06b6d4'
                | '#0891b2'
                | '#0e7490'
                | '#fff7ed'
                | '#ffedd5'
                | '#ea580c'
                | '#c2410c'
                | '#e8e8e8'
                | '#c0c0c0'
                | '#a8a8a8'
                | '#b87333'
                | '#cd7f32'
                | '#ff7f50'
                | '#fa8072'
                | '#ffdab9'
                | '#e6e6fa'
                | '#98ff98'
                | '#808000'
                | '#008080'
                | '#4b0082'
              )
            | null;
          /**
           * 0 = fullstendig gjennomsiktig, 100 = fullstendig ugjennomsiktig
           */
          backgroundColorOpacity?: number | null;
          sectionPadding?: ('none' | 'small' | 'medium' | 'large') | null;
        };
        banner?: {
          image: number | Media;
          imageStyle?: {
            borderRadius?: ('none' | 'small' | 'medium' | 'large' | 'full') | null;
            opacity?: number | null;
            objectFit?: ('cover' | 'contain' | 'fill') | null;
          };
          height?: ('short' | 'medium' | 'tall') | null;
          link?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Konfigurer header og navigasjonsbar
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-settings".
 */
export interface HeaderSetting {
  id: number;
  /**
   * Velg om header skal ha solid farge eller gradient
   */
  backgroundType: 'solid' | 'gradient';
  /**
   * Velg bakgrunnsfarge for header
   */
  backgroundColor?:
    | (
        | '#ffffff'
        | '#000000'
        | '#f9fafb'
        | '#f3f4f6'
        | '#e5e7eb'
        | '#6b7280'
        | '#374151'
        | '#1f2937'
        | '#fee2e2'
        | '#ef4444'
        | '#dc2626'
        | '#b91c1c'
        | '#be123c'
        | '#991b1b'
        | '#eff6ff'
        | '#dbeafe'
        | '#3b82f6'
        | '#2563eb'
        | '#1e40af'
        | '#1e3a8a'
        | '#1e293b'
        | '#f0fdf4'
        | '#d1fae5'
        | '#10b981'
        | '#059669'
        | '#047857'
        | '#065f46'
        | '#fefce8'
        | '#fef3c7'
        | '#f59e0b'
        | '#d97706'
        | '#d4af37'
        | '#b8860b'
        | '#f97316'
        | '#faf5ff'
        | '#ede9fe'
        | '#8b5cf6'
        | '#7c3aed'
        | '#6d28d9'
        | '#5b21b6'
        | '#fdf2f8'
        | '#fce7f3'
        | '#ec4899'
        | '#db2777'
        | '#be185d'
        | '#d946ef'
        | '#c026d3'
        | '#ecfeff'
        | '#cffafe'
        | '#06b6d4'
        | '#0891b2'
        | '#0e7490'
        | '#fff7ed'
        | '#ffedd5'
        | '#ea580c'
        | '#c2410c'
        | '#e8e8e8'
        | '#c0c0c0'
        | '#a8a8a8'
        | '#b87333'
        | '#cd7f32'
        | '#ff7f50'
        | '#fa8072'
        | '#ffdab9'
        | '#e6e6fa'
        | '#98ff98'
        | '#808000'
        | '#008080'
        | '#4b0082'
      )
    | null;
  /**
   * 0 = fullstendig gjennomsiktig, 100 = fullstendig ugjennomsiktig
   */
  backgroundColorOpacity?: number | null;
  /**
   * Velg første farge i gradienten
   */
  gradientColor1?:
    | (
        | '#ffffff'
        | '#000000'
        | '#f9fafb'
        | '#f3f4f6'
        | '#e5e7eb'
        | '#6b7280'
        | '#374151'
        | '#1f2937'
        | '#fee2e2'
        | '#ef4444'
        | '#dc2626'
        | '#b91c1c'
        | '#be123c'
        | '#991b1b'
        | '#eff6ff'
        | '#dbeafe'
        | '#3b82f6'
        | '#2563eb'
        | '#1e40af'
        | '#1e3a8a'
        | '#1e293b'
        | '#f0fdf4'
        | '#d1fae5'
        | '#10b981'
        | '#059669'
        | '#047857'
        | '#065f46'
        | '#fefce8'
        | '#fef3c7'
        | '#f59e0b'
        | '#d97706'
        | '#d4af37'
        | '#b8860b'
        | '#f97316'
        | '#faf5ff'
        | '#ede9fe'
        | '#8b5cf6'
        | '#7c3aed'
        | '#6d28d9'
        | '#5b21b6'
        | '#fdf2f8'
        | '#fce7f3'
        | '#ec4899'
        | '#db2777'
        | '#be185d'
        | '#d946ef'
        | '#c026d3'
        | '#ecfeff'
        | '#cffafe'
        | '#06b6d4'
        | '#0891b2'
        | '#0e7490'
        | '#fff7ed'
        | '#ffedd5'
        | '#ea580c'
        | '#c2410c'
        | '#e8e8e8'
        | '#c0c0c0'
        | '#a8a8a8'
        | '#b87333'
        | '#cd7f32'
        | '#ff7f50'
        | '#fa8072'
        | '#ffdab9'
        | '#e6e6fa'
        | '#98ff98'
        | '#808000'
        | '#008080'
        | '#4b0082'
      )
    | null;
  /**
   * Velg andre farge i gradienten
   */
  gradientColor2?:
    | (
        | '#ffffff'
        | '#000000'
        | '#f9fafb'
        | '#f3f4f6'
        | '#e5e7eb'
        | '#6b7280'
        | '#374151'
        | '#1f2937'
        | '#fee2e2'
        | '#ef4444'
        | '#dc2626'
        | '#b91c1c'
        | '#be123c'
        | '#991b1b'
        | '#eff6ff'
        | '#dbeafe'
        | '#3b82f6'
        | '#2563eb'
        | '#1e40af'
        | '#1e3a8a'
        | '#1e293b'
        | '#f0fdf4'
        | '#d1fae5'
        | '#10b981'
        | '#059669'
        | '#047857'
        | '#065f46'
        | '#fefce8'
        | '#fef3c7'
        | '#f59e0b'
        | '#d97706'
        | '#d4af37'
        | '#b8860b'
        | '#f97316'
        | '#faf5ff'
        | '#ede9fe'
        | '#8b5cf6'
        | '#7c3aed'
        | '#6d28d9'
        | '#5b21b6'
        | '#fdf2f8'
        | '#fce7f3'
        | '#ec4899'
        | '#db2777'
        | '#be185d'
        | '#d946ef'
        | '#c026d3'
        | '#ecfeff'
        | '#cffafe'
        | '#06b6d4'
        | '#0891b2'
        | '#0e7490'
        | '#fff7ed'
        | '#ffedd5'
        | '#ea580c'
        | '#c2410c'
        | '#e8e8e8'
        | '#c0c0c0'
        | '#a8a8a8'
        | '#b87333'
        | '#cd7f32'
        | '#ff7f50'
        | '#fa8072'
        | '#ffdab9'
        | '#e6e6fa'
        | '#98ff98'
        | '#808000'
        | '#008080'
        | '#4b0082'
      )
    | null;
  /**
   * Vinkel for gradient (0-360 grader)
   */
  gradientAngle?: number | null;
  /**
   * Velg tekstfarge fra listen
   */
  textColor:
    | '#ffffff'
    | '#000000'
    | '#f9fafb'
    | '#f3f4f6'
    | '#e5e7eb'
    | '#6b7280'
    | '#374151'
    | '#1f2937'
    | '#fee2e2'
    | '#ef4444'
    | '#dc2626'
    | '#b91c1c'
    | '#be123c'
    | '#991b1b'
    | '#eff6ff'
    | '#dbeafe'
    | '#3b82f6'
    | '#2563eb'
    | '#1e40af'
    | '#1e3a8a'
    | '#1e293b'
    | '#f0fdf4'
    | '#d1fae5'
    | '#10b981'
    | '#059669'
    | '#047857'
    | '#065f46'
    | '#fefce8'
    | '#fef3c7'
    | '#f59e0b'
    | '#d97706'
    | '#d4af37'
    | '#b8860b'
    | '#f97316'
    | '#faf5ff'
    | '#ede9fe'
    | '#8b5cf6'
    | '#7c3aed'
    | '#6d28d9'
    | '#5b21b6'
    | '#fdf2f8'
    | '#fce7f3'
    | '#ec4899'
    | '#db2777'
    | '#be185d'
    | '#d946ef'
    | '#c026d3'
    | '#ecfeff'
    | '#cffafe'
    | '#06b6d4'
    | '#0891b2'
    | '#0e7490'
    | '#fff7ed'
    | '#ffedd5'
    | '#ea580c'
    | '#c2410c'
    | '#e8e8e8'
    | '#c0c0c0'
    | '#a8a8a8'
    | '#b87333'
    | '#cd7f32'
    | '#ff7f50'
    | '#fa8072'
    | '#ffdab9'
    | '#e6e6fa'
    | '#98ff98'
    | '#808000'
    | '#008080'
    | '#4b0082';
  /**
   * Last opp logo for header (kun logo)
   */
  logo?: (number | null) | Media;
  logoSettings?: {
    /**
     * Velg form for logoen
     */
    shape?: ('rectangle' | 'rounded' | 'circle') | null;
  };
  /**
   * Hvis aktivert, vil header følge med når du scroller ned på siden
   */
  sticky?: boolean | null;
  /**
   * Hvis aktivert, vises handlekurv-ikonet i header
   */
  showCartIcon?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Konfigurer footer og kontaktinformasjon
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-settings".
 */
export interface FooterSetting {
  id: number;
  /**
   * Navnet på firmaet som vises i footer
   */
  companyName: string;
  companyNameStyle?: {
    fontSize?: ('small' | 'normal' | 'large' | 'xlarge') | null;
    fontWeight?: ('normal' | 'semibold' | 'bold') | null;
    textColor?:
      | (
          | '#ffffff'
          | '#000000'
          | '#f9fafb'
          | '#f3f4f6'
          | '#e5e7eb'
          | '#6b7280'
          | '#374151'
          | '#1f2937'
          | '#fee2e2'
          | '#ef4444'
          | '#dc2626'
          | '#b91c1c'
          | '#be123c'
          | '#991b1b'
          | '#eff6ff'
          | '#dbeafe'
          | '#3b82f6'
          | '#2563eb'
          | '#1e40af'
          | '#1e3a8a'
          | '#1e293b'
          | '#f0fdf4'
          | '#d1fae5'
          | '#10b981'
          | '#059669'
          | '#047857'
          | '#065f46'
          | '#fefce8'
          | '#fef3c7'
          | '#f59e0b'
          | '#d97706'
          | '#d4af37'
          | '#b8860b'
          | '#f97316'
          | '#faf5ff'
          | '#ede9fe'
          | '#8b5cf6'
          | '#7c3aed'
          | '#6d28d9'
          | '#5b21b6'
          | '#fdf2f8'
          | '#fce7f3'
          | '#ec4899'
          | '#db2777'
          | '#be185d'
          | '#d946ef'
          | '#c026d3'
          | '#ecfeff'
          | '#cffafe'
          | '#06b6d4'
          | '#0891b2'
          | '#0e7490'
          | '#fff7ed'
          | '#ffedd5'
          | '#ea580c'
          | '#c2410c'
          | '#e8e8e8'
          | '#c0c0c0'
          | '#a8a8a8'
          | '#b87333'
          | '#cd7f32'
          | '#ff7f50'
          | '#fa8072'
          | '#ffdab9'
          | '#e6e6fa'
          | '#98ff98'
          | '#808000'
          | '#008080'
          | '#4b0082'
        )
      | null;
  };
  /**
   * Kort beskrivelse av firmaet som vises i footer
   */
  description?: string | null;
  descriptionStyle?: {
    fontSize?: ('small' | 'normal' | 'large') | null;
    textColor?:
      | (
          | '#ffffff'
          | '#000000'
          | '#f9fafb'
          | '#f3f4f6'
          | '#e5e7eb'
          | '#6b7280'
          | '#374151'
          | '#1f2937'
          | '#fee2e2'
          | '#ef4444'
          | '#dc2626'
          | '#b91c1c'
          | '#be123c'
          | '#991b1b'
          | '#eff6ff'
          | '#dbeafe'
          | '#3b82f6'
          | '#2563eb'
          | '#1e40af'
          | '#1e3a8a'
          | '#1e293b'
          | '#f0fdf4'
          | '#d1fae5'
          | '#10b981'
          | '#059669'
          | '#047857'
          | '#065f46'
          | '#fefce8'
          | '#fef3c7'
          | '#f59e0b'
          | '#d97706'
          | '#d4af37'
          | '#b8860b'
          | '#f97316'
          | '#faf5ff'
          | '#ede9fe'
          | '#8b5cf6'
          | '#7c3aed'
          | '#6d28d9'
          | '#5b21b6'
          | '#fdf2f8'
          | '#fce7f3'
          | '#ec4899'
          | '#db2777'
          | '#be185d'
          | '#d946ef'
          | '#c026d3'
          | '#ecfeff'
          | '#cffafe'
          | '#06b6d4'
          | '#0891b2'
          | '#0e7490'
          | '#fff7ed'
          | '#ffedd5'
          | '#ea580c'
          | '#c2410c'
          | '#e8e8e8'
          | '#c0c0c0'
          | '#a8a8a8'
          | '#b87333'
          | '#cd7f32'
          | '#ff7f50'
          | '#fa8072'
          | '#ffdab9'
          | '#e6e6fa'
          | '#98ff98'
          | '#808000'
          | '#008080'
          | '#4b0082'
        )
      | null;
  };
  /**
   * Kontakt e-postadresse
   */
  email: string;
  /**
   * Kontakt telefonnummer
   */
  phone?: string | null;
  /**
   * Åpningstider for butikken (én linje per dag)
   */
  openingHours?: string | null;
  /**
   * Velg bakgrunnsfarge for footer
   */
  backgroundColor:
    | '#ffffff'
    | '#000000'
    | '#f9fafb'
    | '#f3f4f6'
    | '#e5e7eb'
    | '#6b7280'
    | '#374151'
    | '#1f2937'
    | '#fee2e2'
    | '#ef4444'
    | '#dc2626'
    | '#b91c1c'
    | '#be123c'
    | '#991b1b'
    | '#eff6ff'
    | '#dbeafe'
    | '#3b82f6'
    | '#2563eb'
    | '#1e40af'
    | '#1e3a8a'
    | '#1e293b'
    | '#f0fdf4'
    | '#d1fae5'
    | '#10b981'
    | '#059669'
    | '#047857'
    | '#065f46'
    | '#fefce8'
    | '#fef3c7'
    | '#f59e0b'
    | '#d97706'
    | '#d4af37'
    | '#b8860b'
    | '#f97316'
    | '#faf5ff'
    | '#ede9fe'
    | '#8b5cf6'
    | '#7c3aed'
    | '#6d28d9'
    | '#5b21b6'
    | '#fdf2f8'
    | '#fce7f3'
    | '#ec4899'
    | '#db2777'
    | '#be185d'
    | '#d946ef'
    | '#c026d3'
    | '#ecfeff'
    | '#cffafe'
    | '#06b6d4'
    | '#0891b2'
    | '#0e7490'
    | '#fff7ed'
    | '#ffedd5'
    | '#ea580c'
    | '#c2410c'
    | '#e8e8e8'
    | '#c0c0c0'
    | '#a8a8a8'
    | '#b87333'
    | '#cd7f32'
    | '#ff7f50'
    | '#fa8072'
    | '#ffdab9'
    | '#e6e6fa'
    | '#98ff98'
    | '#808000'
    | '#008080'
    | '#4b0082';
  /**
   * 0 = fullstendig gjennomsiktig, 100 = fullstendig ugjennomsiktig
   */
  backgroundColorOpacity?: number | null;
  /**
   * Velg tekstfarge for footer
   */
  textColor:
    | '#ffffff'
    | '#000000'
    | '#f9fafb'
    | '#f3f4f6'
    | '#e5e7eb'
    | '#6b7280'
    | '#374151'
    | '#1f2937'
    | '#fee2e2'
    | '#ef4444'
    | '#dc2626'
    | '#b91c1c'
    | '#be123c'
    | '#991b1b'
    | '#eff6ff'
    | '#dbeafe'
    | '#3b82f6'
    | '#2563eb'
    | '#1e40af'
    | '#1e3a8a'
    | '#1e293b'
    | '#f0fdf4'
    | '#d1fae5'
    | '#10b981'
    | '#059669'
    | '#047857'
    | '#065f46'
    | '#fefce8'
    | '#fef3c7'
    | '#f59e0b'
    | '#d97706'
    | '#d4af37'
    | '#b8860b'
    | '#f97316'
    | '#faf5ff'
    | '#ede9fe'
    | '#8b5cf6'
    | '#7c3aed'
    | '#6d28d9'
    | '#5b21b6'
    | '#fdf2f8'
    | '#fce7f3'
    | '#ec4899'
    | '#db2777'
    | '#be185d'
    | '#d946ef'
    | '#c026d3'
    | '#ecfeff'
    | '#cffafe'
    | '#06b6d4'
    | '#0891b2'
    | '#0e7490'
    | '#fff7ed'
    | '#ffedd5'
    | '#ea580c'
    | '#c2410c'
    | '#e8e8e8'
    | '#c0c0c0'
    | '#a8a8a8'
    | '#b87333'
    | '#cd7f32'
    | '#ff7f50'
    | '#fa8072'
    | '#ffdab9'
    | '#e6e6fa'
    | '#98ff98'
    | '#808000'
    | '#008080'
    | '#4b0082';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  general?:
    | T
    | {
        siteName?: T;
        favicon?: T;
        pageBackgroundType?: T;
        pageBackgroundColor?: T;
        pageBackgroundColorOpacity?: T;
        pageGradientColor1?: T;
        pageGradientColor2?: T;
        pageGradientAngle?: T;
      };
  homeSections?:
    | T
    | {
        sectionType?: T;
        visible?: T;
        hero?:
          | T
          | {
              title?: T;
              titleStyle?:
                | T
                | {
                    fontSize?: T;
                    fontWeight?: T;
                    textColor?: T;
                    textAlign?: T;
                  };
              subtitle?: T;
              subtitleStyle?:
                | T
                | {
                    fontSize?: T;
                    fontWeight?: T;
                    textColor?: T;
                    textAlign?: T;
                  };
              buttonText?: T;
              buttonStyle?:
                | T
                | {
                    backgroundColor?: T;
                    backgroundColorOpacity?: T;
                    textColor?: T;
                    fontSize?: T;
                    padding?: T;
                    borderRadius?: T;
                  };
              buttonLink?: T;
              backgroundType?: T;
              backgroundImage?: T;
              backgroundVideo?: T;
              gradientColor1?: T;
              gradientColor2?: T;
              gradientAngle?: T;
              height?: T;
              textAlign?: T;
              padding?: T;
            };
        featured?:
          | T
          | {
              title?: T;
              titleStyle?:
                | T
                | {
                    fontSize?: T;
                    fontWeight?: T;
                    textColor?: T;
                    textAlign?: T;
                  };
              limit?: T;
              backgroundColor?: T;
              backgroundColorOpacity?: T;
              sectionPadding?: T;
            };
        categories?:
          | T
          | {
              title?: T;
              titleStyle?:
                | T
                | {
                    fontSize?: T;
                    fontWeight?: T;
                    textColor?: T;
                    textAlign?: T;
                  };
              backgroundColor?: T;
              backgroundColorOpacity?: T;
              sectionPadding?: T;
            };
        textSection?:
          | T
          | {
              title?: T;
              titleStyle?:
                | T
                | {
                    fontSize?: T;
                    fontWeight?: T;
                    textColor?: T;
                    textAlign?: T;
                  };
              content?: T;
              contentStyle?:
                | T
                | {
                    fontSize?: T;
                    fontWeight?: T;
                    textColor?: T;
                    textAlign?: T;
                    lineHeight?: T;
                  };
              backgroundColor?: T;
              backgroundColorOpacity?: T;
              sectionPadding?: T;
            };
        banner?:
          | T
          | {
              image?: T;
              imageStyle?:
                | T
                | {
                    borderRadius?: T;
                    opacity?: T;
                    objectFit?: T;
                  };
              height?: T;
              link?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-settings_select".
 */
export interface HeaderSettingsSelect<T extends boolean = true> {
  backgroundType?: T;
  backgroundColor?: T;
  backgroundColorOpacity?: T;
  gradientColor1?: T;
  gradientColor2?: T;
  gradientAngle?: T;
  textColor?: T;
  logo?: T;
  logoSettings?:
    | T
    | {
        shape?: T;
      };
  sticky?: T;
  showCartIcon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-settings_select".
 */
export interface FooterSettingsSelect<T extends boolean = true> {
  companyName?: T;
  companyNameStyle?:
    | T
    | {
        fontSize?: T;
        fontWeight?: T;
        textColor?: T;
      };
  description?: T;
  descriptionStyle?:
    | T
    | {
        fontSize?: T;
        textColor?: T;
      };
  email?: T;
  phone?: T;
  openingHours?: T;
  backgroundColor?: T;
  backgroundColorOpacity?: T;
  textColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}